# -*- coding: utf-8 -*-
"""images.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pXnaAdJuLLjhog_vRGdK0oaOHze_psdB
"""

import cv2

# Load an image from file
image = cv2.imread('example.jpg')

# Check if the image was successfully loaded
if image is None:
    print("Error loading image!")
else:
    # Convert the image to grayscale
    gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Display the original and grayscale images
    cv2.imshow('Original Image', image)
    cv2.imshow('Grayscale Image', gray_image)

    # Wait for a key press and close the windows
    cv2.waitKey(0)
    cv2.destroyAllWindows()